{
 "title": "Set Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "set",
    "query": {
     "query": "label_values(aerospike_sets_device_data_bytes{ns=~\"$namespace\"},set)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(aerospike_sets_device_data_bytes,ns)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Set Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Set Quota Usage",
   "type": "bargauge",
   "description": "Namespace storage usage in percentage",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(aerospike_sets_device_data_bytes{set=~\"$set\"} + aerospike_sets_memory_data_bytes{set=~\"$set\"} ) / aerospike_sets_stop_writes_size{set=~\"$set\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Device Data Bytes",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_sets_device_data_bytes{set=~\"$set\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Device Memory Bytes",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_sets_memory_data_bytes{set=~\"$set\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stop Write Quota (Bytes)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_sets_stop_writes_size{set=~\"$set\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}